# Generated by Django 5.0.6 on 2024-11-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoVestidoor', '0002_alter_productobodega_precio_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('Vendedor', 'Vendedor'), ('Administrador', 'Administrador')], default='Vendedor', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='usuario_personalizado_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='usuario_personalizado_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
