# Generated by Django 5.0.6 on 2024-11-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoVestidoor', '0004_alter_productobodega_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productobodega',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productotienda',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ventaproducto',
            name='subtotal',
            field=models.IntegerField(),
        ),
    ]
