# Generated by Django 5.0.6 on 2024-11-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoVestidoor', '0007_venta_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='boleta_pdf',
            field=models.FileField(blank=True, null=True, upload_to='boletas/'),
        ),
    ]
