# Generated by Django 5.0.6 on 2024-11-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoVestidoor', '0008_venta_boleta_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='productos',
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia')], default='Efectivo', max_length=20),
        ),
    ]
