# Generated by Django 5.0.6 on 2024-12-14 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoVestidoor', '0010_customuser_is_logged_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaproducto',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EcoVestidoor.productotienda'),
        ),
    ]
